University-Finder/students/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.landing_page, name="landing_page"),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('detail/<str:usrn>/', views.userDetail, name="details"),
    path('finder/', views.finderPage, name='univ_finder'),
    path('univDetail/', views.univDetailPage, name='univ_detail'),
    path('donatePay/', views.donatePay, name='donate_pay'),
    path('donate/', views.donate, name='donate'),
    path('delete/', views.deleteUser, name='delete_user'),
]

University-Finder/u_finder/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static

# from django.views.static import serve
from django.conf.urls import url



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),    
    # url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}),
]

#urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

University-Finder/students/models.py
from django.db import models

# Create your models here.


class Level(models.Model):
    CATEGORY = (
        ("High School", "High School"),
        ("Under Graduate", "Under Graduate"),
    )

    level_code = models.IntegerField(primary_key=True)
    level_name = models.CharField(max_length=200, null=True, choices=CATEGORY)

    def __str__(self):
        return self.level_name


class Degree(models.Model):
    degree_code = models.CharField(primary_key=True, max_length=200)
    degree_name = models.CharField(max_length=200, null=True)
    level_code = models.ForeignKey(Level, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.degree_name


class Student(models.Model):
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    student_id = models.CharField(primary_key=True, max_length=200)
    email = models.EmailField(max_length=200, null=True)
    gender = models.CharField(max_length=200, null=True)
    password = models.CharField(max_length=200, null=True)
    level = models.ForeignKey(Level, null=True, on_delete=models.SET_NULL)
    degree_name = models.ForeignKey(
        Degree, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.student_id


class University(models.Model):
    CATEGORY = (
        ("Under Graduate", "Under Graduate"),
        ("Post Graduate", "Post Graduate"),
    )

    CATEGORY1 = (
            ("B.Tech", "B.Tech"),
            ("MA", "MA"),
            ("B.Sc", "B.Sc"),
            ("BS", "BS"),
            ("BA LLB", "BA LLB"),
            ("B.Des.", "B.Des."),
            ("MBA", "MBA"),
            ("MS", "MS"),
            ("MBBS", "MBBS"),
            ("B.Arch", "B.Arch"),
            ("BE", "BE"),
            ("M.Sc", "M.Sc"),
            ("BA", "BA"),
            ("DO", "DO"),
        )

    CATEGORY2 = (
            ("CSE", "CSE"),
            ("English", "English"),
            ("EECS", "EECS"),
            ("ASL", "ASL"),
            ("GD", "GD"),
            ("HRMS", "HRMS"),
            ("AE", "AE"),
            ("CSD", "CSD"),
            ("MBBS", "MBSS"),
            ("UPA", "UPA"),
            ("ENI", "ENI"),
            ("Physics", "Physics"),
            ("AS", "AS"),
            ("ECE", "ECE"),
            ("HCI", "HCI"),
            ("History", "History"),
            ("Economics", "Economics"),
            ("MECS", "MECS"),
            ("IB", "IB"),
            ("EEE", "EEE"),
            ("Liberal Arts", "Liberal Arts"),
            ("FD", "FD"),
            ("ENT", "ENT"),
            ("CE", "CE"),
        )

    CATEGORY3 = (
            ("India", "India"),
            ("USA", "USA"),
            ("Australia", "Australia"),
            ("Japan", "Japan"),
            ("Singapore", "Singapore"),
            ("China", "China"),
            ("UK", "UK"),
        )

    university_id = models.CharField(primary_key=True, max_length=200)
    university_name = models.CharField(max_length=200, null=True)
    degree = models.CharField(max_length=200, null=True, choices=CATEGORY1)
    course = models.CharField(max_length=200, null=True, choices=CATEGORY2)
    level = models.CharField(max_length=200, null=True, choices=CATEGORY)
    location = models.CharField(max_length=200, null=True, choices=CATEGORY3)
    Website = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.university_id

class University_Info(models.Model):
    univ_id = models.CharField(primary_key=True, max_length=200)
    univ_name = models.CharField(max_length=200, null=True)
    research_paper = models.IntegerField(null=True)
    placement_percent = models.DecimalField(null=True, max_digits=4, decimal_places=2)
    courses_available = models.IntegerField(null=True)
    comp_visit = models.IntegerField(null=True)
    avg_place_amt = models.DecimalField(null=True, max_digits=5, decimal_places=2)
    high_place_amt = models.DecimalField(null=True, max_digits=5, decimal_places=2)
    min_place_amt = models.DecimalField(null=True, max_digits=5, decimal_places=2)
    web = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.univ_name


class Suggestion(models.Model):
    suggestion_code = models.IntegerField(primary_key=True)
    topic1 = models.CharField(max_length=200, null=True)
    topic2 = models.CharField(max_length=200, null=True)
    topic3 = models.CharField(max_length=200, null=True)
    student_id = models.ForeignKey(
        Student, null=True, on_delete=models.SET_NULL)
    university_id = models.ManyToManyField(University)
    code = str(suggestion_code)

    def __str__(self):
        return self.code


class univDegree(models.Model):
    univ_deg_id = models.IntegerField(primary_key=True)
    univ_deg_name = models.CharField(max_length=200, null=True)
    university_id = models.ForeignKey(
        University, null=True, on_delete=models.SET_NULL)
    id = str(univ_deg_id)

    def __str__(self):
        return self.univ_deg_name


class Topics(models.Model):
    topic = models.CharField(max_length=200, null=True)
    univ_deg_id = models.ForeignKey(
        univDegree, null=True, on_delete=models.SET_NULL)
    id = str(univ_deg_id)



class Courses(models.Model):
    course = models.CharField(max_length=200, null=True)
    univ_deg_id = models.ForeignKey(
        univDegree, null=True, on_delete=models.SET_NULL)
    id = str(univ_deg_id)

class DonationInfo(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=200, null=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    street = models.CharField(max_length=200, null=True)
    zip_code = models.IntegerField(null=True)
    city = models.CharField(max_length=200, null=True)
    country = models.CharField(max_length=200, null=True)
    

University-Finder/students/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField()
    last_name = forms.CharField()

    username.widget.attrs.update({'placeholder': "Username"})
    password1.widget.attrs.update({'placeholder': 'New Password'})
    password2.widget.attrs.update({'placeholder': 'Re-enter Password'})
    first_name.widget.attrs.update({'placeholder': 'First Name'})
    last_name.widget.attrs.update({'placeholder': 'Surname'})

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class DetailsForm(ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name',
                  'student_id', 'email', 'level', 'degree_name']


NUMS = [
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
]

class CHOICES(forms.Form):
    NUMS = forms.CharField(widget=forms.RadioSelect(choices=NUMS))

University-Finder/students/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


from .models import *
from .forms import *
from .filter import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import *
from django import forms

import re


@login_required(login_url='login')
def home(request):
    user = User.objects.all()
    university = University.objects.all()

    

    total_users = user.count()
    total_university = university.count()
    context = {
        'total_users': total_users,
        'total_university': total_university,
    }
    return render(request, 'students/home.html', context)

def landing_page(request):  

    context = {}

    return render(request, 'students/index.html', context)

@unauthenticated_user
def registerPage(request):

    username_regex = '^(?=[a-zA-Z0-9._]{8,20}$)(?!.*[_.]{2})[^_.].*[^_.]$'
    

    # Only contains alphanumeric characters, underscore and dot.
    # Underscore and dot can't be at the end or start of a username (e.g _username / username_ / .username / username.).
    # Underscore and dot can't be next to each other (e.g user_.name).
    # Underscore or dot can't be used multiple times in a row (e.g user__name / user..name).
    # Number of characters must be between 8 to 20.


    if request.method == "POST":
        fname = request.POST.get('fname')
        sname = request.POST.get('sname')
        usern = request.POST.get('username')
        password1 = request.POST.get('one_p')
        password2 = request.POST.get('second_p')
        date = request.POST['date']
        month = request.POST['month']
        year = request.POST['year']
        gen = request.POST['gender']

        if(not re.search(username_regex, usern)):
            messages.error(request, "Please choose a decent username.")
            return redirect('register')

        if(len(fname) == 0 or len(sname) == 0):
            messages.error(request, "Found some empty fields. Please fill it.")
        
        if(password1 != password2):
            messages.error(request, "Re-entered password do not match.")
            return redirect('register')

        user = User.objects.create_user(
            first_name = fname,
            last_name = sname,
            username = usern,
            password = password1,
        )
        user.save()            


        st = Student(
            student_id = usern,
            password = password1,
            first_name = fname,
            last_name = sname,
            gender = gen,
        )
        st.save()

        messages.success(request, "Account was created for " + usern + ".")
        return redirect('login')

    context = {}
    return render(request, 'students/register.html', context)


@unauthenticated_user
def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Error : Username or Password is incorrect.")

    context = {}
    return render(request, 'students/login.html', context)

def donatePay(request):
    context = {}

    if request.method == "POST":
        amount = request.POST.get('amount')

        if amount == "":
            messages.error(request, "Input field empty. Please enter something.")
            return redirect('donate_pay')

        response = redirect('donate')
        response.set_cookie('amount', amount)
        return response
        
    return render(request, 'students/donate-pay.html', context)

    
    

def donate(request):
    amount = request.COOKIES['amount']
    regex_email = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'

    context = {
        'amount': amount,
    }

    if request.method == "POST":
        email = request.POST.get('email')
        first_name = request.POST.get('f_name')
        last_name = request.POST.get('l_name')
        street = request.POST.get('street')
        zip_code = request.POST.get('zip_code')
        city = request.POST.get('city_name')
        country = request.POST['country_name']
        card_no = request.POST.get('card_number')
        date = request.POST['date']
        month = request.POST['month']
        CVV = request.POST.get('CVV')

        if(not re.search(regex_email, email)):
            messages.error(request, "Please enter correct Email Address.")
            return redirect('donate')
        
        if(len(first_name) == 0 or len(last_name) == 0 or len(street) == 0 or len(city) == 0):
            messages.error(request, "Found some empty fields. Please fill it.")
            return redirect('donate')

        if( len(str(zip_code)) != 6) :
            messages.error(request, "Please enter the correct Zip Code. Number of digits do not match.")
            return redirect('donate')

        if( len(str(card_no)) < 13 and len(str(card_no)) > 19):
            messages.error(request, "Please enter the correct Card Number. Number of digits do not match.")
            return redirect('donate')
        
        if( len(str(CVV)) < 3 and len(str(CVV)) > 4 ):
            messages.error(request, "Please enter correct CVV.")
            return redirect('donate')

        
        don_inf = DonationInfo(
            email = email,
            first_name = first_name,
            last_name = last_name, 
            street = street,
            zip_code = int(zip_code),
            city = city,
            country = country,
        )
        don_inf.save()

        return redirect('landing_page')


    return render(request, 'students/donate.html', context)

@login_required(login_url='login')
def logoutUser(request):

    if request.method == "POST":
        logout(request)
        return redirect('landing_page')

    return render(request, 'students/logout_page.html')

@login_required(login_url='login')
def deleteUser(request):
    user = request.COOKIES['username']    
    name = request.user.get_full_name()
        

    context = {
        "user": user,
        "name": name,
    }

    if request.method == "POST":
        u = User.objects.get(username = user)
        logout(request)
        u.delete()
        return redirect('landing_page')

    return render(request, 'students/del_acc.html', context)

@login_required(login_url='login')
def userDetail(request, usrn):
    detail = Student.objects.get(student_id=usrn)
    form = DetailsForm(instance=detail)
    print(form)

    if request.method == "POST":
        if request.POST.get('para') == "data_update":
            form = DetailsForm(request.POST, instance=detail)
            if form.is_valid():
                firstName = form.cleaned_data.get('first_name')
                lastName = form.cleaned_data.get('last_name')
                Email = form.cleaned_data.get('email')
                st_id = form.cleaned_data.get('student_id')
                lvl = form.cleaned_data.get('level')
                deg = form.cleaned_data.get('degree_name')

                Student.objects.filter(student_id=usrn).update(
                    first_name=firstName, last_name=lastName, email=Email, student_id=st_id, level=lvl, degree_name=deg)

                return redirect('home')
        
        elif request.POST.get('para') == "delete-acc":
            request = redirect('delete_user')
            request.set_cookie('username', usrn)
            return request

    

    context = {'form': form}
    return render(request, 'students/user-detail.html', context)

@login_required(login_url='login')
def finderPage(request):

    university = University.objects.all()

    myFilter = UniversityFilter(request.GET, queryset=university)
    univ = myFilter.qs
    print(myFilter.form)
    context = {
        'univ': univ,
        'myFilter': myFilter,
    }
    return render(request, 'students/finder.html', context)


@login_required(login_url='login')
def univDetailPage(request):

    univ = University_Info.objects.all()

    myFil = universityInfoFilter(request.GET, queryset=univ)
    u = myFil.qs
    m = u.first()

    print(m)
    print(myFil)
    print(myFil.form)

    context = {
        'u': u,
        'myFil': myFil,
        'm': m,
    }

    return render(request, 'students/univ_info.html', context)

University-Finder/students/templates/students/del_acc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"> 
    <title>University Finder</title>
    <style>
        body{
            font-family: 'Poppins', sans-serif;
            background-color: orange;
        }
       .app{
            margin-top: 50px;
            margin-left: 300px;
            font-size: 30px;
       }
       .app a{
            text-decoration: none;
            color: rgb(70, 63, 63);
            font-size: 40px;
        }
        .content{
            margin-left: 600px;
            margin-right: 600px;
            border: 1px solid black;
            padding: 25px;
            padding-bottom: 100px;
            padding-top: 40px;
            background-color: white;
        }
        .content p{
            line-height: 20px;            
        }
        #res{
            width: 270px;
        }
        #sub{
            margin-top: 30px;
            background-color: brown;
            width: 270px;
            height: 45px;
            color: white;
        }
        h1, h2{
            color: black;
        }

        p{
            color: blue;
            font-weight: bolder;
        }
        #name{
            color: brown;
            font-weight: bolder;
            
        }
        #frm{
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="app">
        <a href="{% url 'landing_page' %}">University Finder</a> 
    </div>
    <hr>
    <br>
    <div class="content">
    
        <h1> Delete Your Account </h1>
        <p>Hi <span id="name"><b>{{name}}</b></span>,</p>
        <p>We are sorry to hear you would like to delete your account.</p>
        <p>Your account has been deleted successfully.</p>

        <h2> Keeping Your Data Safe</h2>
        <p> Nothing is more important to us but you keep your data safe and secure in our University Finder Website.<br><br> Please put your trust on us as we shall make no compromises on it.</br></p>
        
        <hr>

        <h3>Why are you deleting your account?</h3><br>
        <form action="" method="POST" id="frm">
            {% csrf_token %}
            <select class="option" id="res" name="reason">
                <option>Unsatisfied </option>
                <option>Service Not Good </option>
                <option>Rather Not Specify</option>
            </select><br><br>

            <input id="sub" type="submit" value="Go To Home">
        </form>
    </div>

</body>
</html>

University-Finder/students/templates/students/donate-pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donate Now</title>
    <style>
        .container{
            display: flex;
            flex-direction: row;
        }
        .pay {
            width: 50%;
            margin-top: 70px;
            
        }
        .photo{
            width: 50%;
            margin-top: 100px;
        }
        .photo img{
            margin-left: 500px;
        }
        .photo p{
            width: 350px;
            margin-left: 500px;
            text-align: right;
        }

        #id_inp_amt{
            width: 300px;
            height: 70px;
            font-size: 18px;
        }

        h3 span{
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            font-size: 20px;
        }
        h1 {
            padding-left: 30px;
        }
        h3 {
            padding-left: 60px;
        }

        #dollar{
            padding: 10px;
            font-size: 25px;
        }
        #id_sub_btn{
            width: 300px;
            height: 40px;
            background-color:darkblue;
            color: white;
            font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            margin-left: 42px;
            width: 315px;
            height: 50px;
        }
        .navbar{
            margin-top: 50px;
            margin-left: 300px;
            font-size: 30px;
        }
        .navbar a{
            text-decoration: none;
            color: black;
        }
        #mssg{
            margin-left:30px;
            color: red;
        }
        /* has been used to disappear the arrows in number input type*/
        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'landing_page' %}">University Finder</a> 
    </div>
    <hr>
    <div class="container">        
        <div class="photo">
            <img src="https://miro.medium.com/max/3640/1*0ESRdJgzIKVIKsvmzPEWnQ.jpeg" height="250" width="350" alt="">
            <p><b>We are proudly non-profit, </b>non-corporate and non-compromised.
            Thousands of people like you help us stand up for a healthy internet for all. 
            We rely on donations to carry out our mission to keep the Web open and free.
            <b>Will you give today?</b></p>
        </div>
        <div class="pay">
            <h1>Donate now</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <span id="dollar">$</span><input type="number" value="Enter a Amount" name="amount" id="id_inp_amt">
                {% for message in messages %}
                    <p id="mssg">{{ message }}</p>
                {% endfor %}
                <h3>Confirm Payment&nbsp<img src="https://cdn.icon-icons.com/icons2/2440/PNG/512/lock_icon_148524.png" width="20px" height="20px" alt=""><span>Secure</span></h3>
                <input type="submit" value="Pay Now" id="id_sub_btn">
            </form>
        </div>
    </div>
</body>
</html>

University-Finder/students/templates/students/finder.html
{%  extends 'students/main.html' %}
{% load static %}
{% block content %}
<style>
	#bhy{
		margin-left: 650px;
		margin-right: 650px;
	}

	#sn-btn, #id_university_name, #id_degree, #id_course, #id_level, #id_location{
		width: 100%;
		height: 45px;
	}
	#r{
		background-color: lightblue;
		padding-bottom: 10px;
		padding-top: 10px;
	}

</style>

<section>

	<div class="row" id="r">
		<div class="col">
			<div class="card card-body" id="bhy">
				<form method="get">

					{% for i in myFilter.form %}

						<p>{{i.label}} :</p>
						<p>{{i}}</p>
						<hr>

					{% endfor %}

				<button class="btn btn-primary" id="sn-btn" type="submit">Search</button>
			</form>
			</div>
		</div>
		
	</div>
	<br>

	<div class="row">
		<div class="col-md">
			<div class="card card-body">
				<table class="table table-sm">
					<tr>
						<th>University Name</th>
						<th>Degree</th>
						<th>Course</th>
						<th>Location</th>
						<th>Website</th>
					</tr>

					{% for i in univ %}
						<tr>
							<td>{{i.university_name}}</td>
							<td>{{i.degree}}</td>
							<td>{{i.course}}</td>
							<td>{{i.location}}</td>
							<td><a target="_blank" href = "{{i.Website}}"> {{i.Website}} </a></td>        	
						</tr>
					{% endfor %}

				</table>
			</div>
		</div>
	</div>

</section>

{% endblock %}

University-Finder/students/templates/students/home.html
{% extends 'students/main.html' %} 
{% block content %} 

<br><br>

<style>
    .typing{
        color: purple;
    }
</style>

<h1 style="font-family:verdana; text-align: center;">COLLEGE FINDER FOR HIGH SCHOOL AND UNDERGRADUATE STUDENTS</h1><br><br>

<h2 style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; text-align: center; color: darkblue;"> Which one could be the best college for you ?</h2> <br> <br>
<h2 style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; text-align: center; color: black;"> Maybe <span class="typing">Harvard</span></h2>

<br><br>

{% include 'students/status.html' %}

<br />

<script>
    $(document).ready(function(){
        var typed = new Typed(".typing", {
        strings: ["Harvard", "Massachusetts Institute of Technology", "Oxford University ", "Wharton School of Business", "University of Waterloo"],
        typeSpeed: 100,
        backSpeed: 80,
        loop: true
    });
    });
</script>

 

{% endblock %}

University-Finder/students/templates/students/univ_info.html
{%  extends 'students/main.html' %}
{% load static %}
{% block content %}

<style>
	.univ-info-s{
		height: 100vh;
	}
	#id_univ_name{
		width: 400px;
		height: 60px;
	}
	#web{
		width: 500px;
		margin-top: 50px;
	}
	#courses{
		width: 500px;
		margin-left: 300px;
		margin-top: 50px;
	}
	#bdy{
		text-align: center;
	}
</style>

<br>
	<section class="univ-info-s">
	<div class="row">
		<div class="col">
			<div class="card card-body" id="bdy">
				<form method="get">

					<!-- {% for i in myFil.form %} -->

						<p> {{ myFil.form.as_p }} </p>
						
						<hr>

					<!-- {% endfor %} <p >{{ i }}</p> -->

				<button class="btn btn-primary" type="submit">Search</button>
			</form>
			</div>
		</div>
		
	</div>
	<br>
	<div class="row">

			<div class="col">
				<div class="col-md">
					<div class="card text-center text-white mb-3" id = "total-orders">
						<div class="card-header">
							<h5 class="card-title"><b>Number of Research Papers Released every Year</b></h5>
						</div>
						<div class="card-body">
							<h3 class="card-title">{{ m.research_paper }}</h3>
						</div>
					</div>
				</div>
			</div>

			<div class="col">
				<div class="col-md">
					<div class="card text-center text-white mb-3" id = "total-orders">
						<div class="card-header">
							<h5 class="card-title"><b>Companies Visiting Campus for Placements</b></h5>
						</div>
						<div class="card-body">
							<h3 class="card-title">{{ m.comp_visit }} </h3>
						</div>
					</div>
				</div>
			</div>

			<div class="col">
				<div class="col-md">
					<div class="card text-center text-white mb-3" id = "total-orders">
						<div class="card-header">
							<h5 class="card-title"><b>Placement Percentage</b></h5>
						</div>
						<div class="card-body">
							<h3 class="card-title">{{ m.placement_percent }} </h3>
						</div>
					</div>
				</div>
			</div>

		</div>

		<div class="row">

			<div class="col">
				<div class="col-md" id="courses">
					<div class="card text-center text-white mb-3" id = "total-orders">
						<div class="card-header">
							<h5 class="card-title"><b>Courses Available</b></h5>
						</div>
						<div class="card-body">
							<h3 class="card-title">{{ m.courses_available }} </h3>
						</div>
					</div>
				</div>
			</div>

			<div class="col">
				<div class="col-md" id="web">
					<div class="card text-center text-white mb-3" id = "total-orders">
						<div class="card-header">
							<h5 class="card-title"><b>Website Link</b></h5>
						</div>
						<div class="card-body">
							<h3 class="card-title"><a style = "text-decoration: none; color: white;" target="_blank" href = "{{ m.web }}"> {{ m.web }} </a></h3>
						</div>
					</div>
				</div>
			</div>

		</div>
</section>
{% endblock %}

University-Finder/students/templates/students/user-detail.html
{% extends 'students/main.html' %} 
{% load static %}
{% block content %}

<style>
	.user-de{
		margin-left: 700px;
		margin-right: 700px;
	}
	#id_first_name, #id_last_name, #id_student_id, #id_email, #id_level, #id_degree_name, #sub-btn{
		width: 100%;
		height: 45px;
	}
	.usr-s{
		background-color:skyblue;
	}
	#sub-btn{
		margin-bottom: 30px;
		background-color: green;
		color: white;
	}
	#del-btn{
		width: 100%;
		height: 45px;
		background-color: red;
		color: white;
		margin-bottom: 15px;
	}
</style>

<section class="usr-s">
	<br>
	<div class="user-de">
		<form action="" method="POST">			
			{% csrf_token %}

			{% for i in form %}

				<p> {{i.label}} :</p> 
				<p> {{i}} </p>
				<hr>

			{% endfor %}

			<input type="hidden" name="para" id="para" value="data_update">
			<input type = "submit" id="sub-btn" value = " Save ">

		</form>
		<form action="" method="POST">
			{% csrf_token %}
			<input type="hidden" name="para" id="para" value="delete-acc">
			<input type="submit" name="del-btn" id="del-btn" value="Delete Account">
		</form>
		
	</div>
</section>


{% endblock %}